apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-visualizer-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-visualizer-auth
  template:
    metadata:
      labels:
        # app 이름 매칭
        app: batch-visualizer-auth
    spec:
      containers:
        - name: batch-visualizer-auth
          image: twofootdog/project-repo:batch-visualizer-auth
          ports:
            # port 매칭
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: docker-secret