# apiVersion: v1
# kind: Service
# metadata:
#   name: webflux-repo-test-service
# spec:
#   ports:
#     - name: "test-http"
#       port: 8080
#       protocol: TCP
#       # port 매칭
#       targetPort: 8080
#   selector:
#     # app 이름 매칭
#     app: webflux-repo-test
#   type: LoadBalancer
